### ISSUE TITLE
Not getting the correct results

### ISSUE THREAD

**Issue by milind-prajapat** [opensourcesblog/sudoku#1]
Here is the sudoku,
0 0 0 0 0 0 2 0 0
0 8 0 0 0 7 0 9 0
6 0 2 0 0 0 5 0 0
0 7 0 0 6 0 0 0 0
0 0 0 9 0 1 0 0 0
0 0 0 0 2 0 0 4 0
0 0 5 0 0 0 6 0 3
0 9 0 4 0 0 0 7 0
0 0 6 0 0 0 0 0 0
I am not getting the correct results using your source code.

**Comment by Wikunia** [comment]
Thanks for opening the issue.
Please add the following information:
- Does it throw an error?
- Does it think it's infeasible but it isn't?
- Does it compute a solution that's just different from the one you had in mind?

Furthermore I recommend checking out my new project for these kind of problems here: https://github.com/Wikunia/ConstraintSolver.jl as that gets actively developed.

**Comment by milind-prajapat** [comment]
It doesn't throw any errors nor it shows that its infeasible but the result
is not correct. The result still contains zeros, i.e., not solved
completely but still returned as solution.

**Comment by Wikunia** [comment]
Please share the program here such that I can run the exact same thing as you.

**Comment by Wikunia** [comment]
Oh I'm sorry. I think this program doesn't implement backtracking yet. Which means it only applies all the reductions possible. 

It was more a project for testing stuff out and blog about it. If you're interested in an actual solver please have a look at some other repositories depending on your need.

In Python v you can always use or-tools for a full Constraint solver
There are specialized sudoku solvers written in a variety of languages i.e "GitHub - t-dillon/tdoku: A fast Sudoku solver and generator with a benchmark suite for comparing the fastest known solvers." https://github.com/t-dillon/tdoku

**Comment by milind-prajapat** [comment]
Thanks, I'll check it out. And I checked out your blog, it was cool. I am a
learner, I was coding that on my own. The information given on your blog
was enough for me to code. Thanks a lot.

**Comment by Wikunia** [comment]
Oh in that case you might be interested in the Str8ts post I did afterwards. There I explain backtracking as well. You could even try to add it for the sudoku solver.

If you're interested in constraint programming and not especially in doing it in Python: I currently have a series of roughly 30 posts about my new project using the Julia programming language about it.

It's much more performant but the blog posts are in less detail as the project is getting quite big.

If you have questions about that series though I'm more eager to help and improve it than for this one as I'm not working on this one anymore.

**Comment by milind-prajapat** [comment]
Thanks a lot, but I am doing it in python specifically. I haven't tried
Julia yet, not familiar at all with that. Well I tried a backtracking brute
force solution at first but it was taking a lot time.
Now I am combining the constraint programming along with backtracking.
Can you share the topic of your new project with me? Any links, If I am
interested I will be following that for sure.

**Comment by Wikunia** [comment]
My posts about it start here: https://opensourc.es/blog/constraint-solver-1/
The project itself is here: https://github.com/Wikunia/ConstraintSolver.jl

I think one can do something like that with Python it will be just way slower.

**Comment by milind-prajapat** [comment]
Thanks, I'll check it out.
